name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './myapp/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./myapp
      
      - name: Build
        run: npm run build
        working-directory: ./myapp
        env:
          VITE_SUPABASE_URL: https://magmikrrbiyqtabrhyxy.supabase.co
          VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ21pa3JyYml5cXRhYnJoeXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDUwMzIsImV4cCI6MjA3NDIyMTAzMn0.YmM97XwpCe0eO2pzFuVNJbAETDLiqRvRnzXjJDoWbGo
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './myapp/dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4